### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by KateSakharova**
It is not a perfect-nextflow pipeline, but it does what it should :)

### CODE REVIEW

**Comment by mberacochea** [comment]
@KateSakharova I would merge this... did a very quick read, and it's good :+1:

**Review by mberacochea — APPROVED** [review]
:shipit:

**Comment by ochkalova** [comment]
I have nothing to add, all good 👍🏻

**Review by ochkalova — APPROVED** [review]
Thanks for the work!

**Pull request merged**
